### ISSUE TITLE
Issue in GitHub Login

### ISSUE THREAD

**Issue by Siddhant-K-code** [nileshsah/harwest-tool#10]
Facing this issue: 
![image](https://user-images.githubusercontent.com/55068936/102956021-50538e80-44fd-11eb-9be0-ce05a889dffc.png)
```
Traceback (most recent call last):
  File "d:\python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "d:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Python\Scripts\harwest.exe\__main__.py", line 9, in <module>
  File "d:\python\lib\site-packages\harwest\harwest.py", line 106, in main
    args.func(args)
  File "d:\python\lib\site-packages\harwest\harwest.py", line 77, in codeforces
    CodeforcesWorkflow(configs).run(start_page_index=args.start_page)
  File "d:\python\lib\site-packages\harwest\lib\codeforces\workflow.py", line 92, in run
    self.repository.push()
  File "d:\python\lib\site-packages\harwest\lib\utils\repository.py", line 52, in push
    self.git.push(*args)
  File "d:\python\lib\site-packages\git\cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "d:\python\lib\site-packages\git\cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "d:\python\lib\site-packages\git\cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git push origin master
  stderr: 'Logon failed, use ctrl+c to cancel basic credential prompt.
bash: /dev/tty: No such device or address
error: failed to execute prompt script (exit code 1)
fatal: could not read Username for 'https://github.com': No such file or directory'

```
I filled all correct details at both places!!

**Comment by Siddhant-K-code** [comment]
*Issue Resolved*

Problem was with git version, i.e. `our git should be updated` -- Can be added in Documentation
